name: maven build workflow

on:
  workflow_dispatch:

jobs:
  maven_build:
    runs-on: ubuntu-latest
    if: ${{ github.ref_name == 'main' }}
    steps:
      - name: Checkout repo branch
        uses: actions/checkout 387ac29b308b003ca37ba93a6cab5eb57c8f5f93
        with:
          repository: sriram0157/spring-petclinic
          ref: main
          path: spring-petclinic

      - name: Install Java and Maven
        run: |
          sudo apt update
          sudo apt install openjdk-17-jdk -y
          sudo apt install maven -y

      - name: Build with Maven
        run: mvn -B package --file spring-petclinic/pom.xml
