

name: steps testing

on:
  push:
    branches:
      - "*"

jobs:
  test:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest,windows-latest]
     
        node-version: [16, 18]
        exclude:
          - os: windows -latest
            node-version: 18
        include:
          - os: ubuntu -latest
            node-version: 18
        
    steps:
      - name: checkout
        uses: actions/checkout@v7
        
      - name: install node js
        uses: actions/setup-node@v7
        with:
          node-version: ${{ matrix. node-version }}
      - name: summary for jobs   
        run: |
          echo "result ${{matrix. node-version}} is passed" >> $GITHUB_STEP_SUMMARY
