name: Dynamic

on:
  push:
    branches:
      - "*"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Install chart version
        run: |
          echo "BUILD_ID=$(date +%d-%m-%y)" >> $GITHUB_ENV

      - name: Print dynamic
        run: |
          echo "${{env.BUILD_ID}}"
