name: Dynamic
on:
  push:
    branches: "*"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: action/checkout@v7
        
      - name: install chart version
        run: |
          echo "BUILD_ID = $(date +%d-%m-%y)
