
name: steps testing

on:
  push:
    branches:
      - "*"

jobs:
  test:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest,windows-latest]
     
        node-version: [16, 18]
        exclude:
        - os: windows -latest
          node-vesrion: 18
        include:
        - os: ubuntu -latest
          node-version: 18
    steps:
      - name: checkout
        uses: actions/checkout@v7
        
      - name: install node js
        uses: actions/setup-node@v7
        with:
          node-version: ${{ matrix. node-version }}
