name: steps testing

on:
  push:
    branches:
      - "*"

jobs:
  build_id:
    runs-on: ubuntu-latest
    outputs:
      value_id: ${{ steps.version.outputs.version }}
    steps:
      - name: sample data
        id: version
        run: |
          echo "version=1.2.3" >> $GITHUB_OUTPUT

      - name: print outputs
        run: |
          echo "build version is ${{ steps.version.outputs.version }}"

  test-data:
    runs-on: ubuntu-latest
    needs: build_id
    steps:
      - name: demo
        run: |
          echo "jobs version id is ${{ needs.build_id.outputs.value_id }}"
